.\" Manpage for tools.
.\" Contact contact@digitalleaves.com for comments or help.
.TH man 1 "17 August 2022" "2.90" "tools man page"
.SH NAME
tools \- regular expression match / tester
.SH SYNOPSIS

command line input:

tools [-[hirPpEeo]] REGEXP SOURCE

input from file:

tools -x REGEXP_PATH -f SOURCE_PATH

.SH DESCRIPTION
Command line testing application for "c++ standard regex implemnetation", aka "#include <regex>".
.SH OPTIONS
    -h, --help
        Displays a friendly help message.

    -i, --ignore_case
        ignore case

    -r, --version
        Displays the software version.


.SH BUGS
No known bugs.
.SH AUTHOR
Brian Preston (brian8181@gmail.com)