# @name     tools2
# @file:    makefile
# @date:    Mon Aug 17 09:38:40 AM CDT 2026
# @version: version 0.0.1

# g++ warnings
#-Wall -Wextra -Wpedantic -Wshadow -Wconversion -Werror -Wundef
#-fsanitize=undefined,address -Wfloat-equal -Wformat-nonliteral
#-Wformat-security -Wformat-y2k -Wformat=2 -Wimport -Winvalid-pch
#-Wlogical-op -Wmissing-declarations -Wmissing-field-initializers
#-Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn
#-Wnested-externs -Wpacked -Wpointer-arith -Wredundant-decls
#-Wstack-protector -Wstrict-null-sentinel -Wswitch-enum -Wwrite-strings

SHELL:=bash

APP=tools2
CXX=g++
CXXFLAGS=-Wall -std=c++20 -fPIC
CXXEXTRA=-Wno-template-body
CXXCPP=
LDFLAGS=
LIBS=

SRC = src
BLD = build
OBJ = build
TST = build

# lib settings
LIBS=-L/usr/lib -L/usr/lib64 -L/usr/local/lib -L/usr/local/lib64
INCLUDES=-I/usr/local/include/cppunit/
LDFLAGS=$(INCLUDES) $(LIBS)

ifndef RELEASE
	CXXFLAGS +=-g -DDEBUG
endif

ifdef CYGWIN
	CXXFLAGS +=-DCYGWIN
	LDFLAGS += -lfmt -lcppunit.dll
else
	LDFLAGS += -lfmt -lcppunit
endif

all: $(BLD)/tools2 $(BLD)/libtools2.so $(BLD)/libtools2.a $(BLD)/TEST_tools2 #

$(BLD)/tools2: $(OBJ)/main.o $(OBJ)/tools2.o
	 $(CXX) $(CXXFLAGS) $(OBJ)/main.o $(OBJ)/tools2.o -o $(BLD)/tools2 #

$(BLD)/libtools2.so: $(OBJ)/main.o $(BLD)/tools2.o
	$(CXX) $(CXXFLAGS) $(CXXEXTRA) --shared $(OBJ)/main.o $(BLD)/tools2.o -o $(BLD)/libtools2.so
	-chmod 755 $(BLD)/libtools2.so

$(BLD)/libtools2.a: $(OBJ)/main.o $(BLD)/tools2.o
	-ar rvs $(BLD)/libtools2.a $(OBJ)/main.o $(BLD)/tools2.o
	-chmod 755 $(BLD)/libtools2.a

$(OBJ)/tools2.o: $(SRC)/tools2.cpp
	$(CXX) $(CXXFLAGS) $(CXXEXTRA) -c $(SRC)/tools2.cpp -o $(OBJ)/tools2.o

$(BLD)/TEST_tools2: $(OBJ)/tools2.o $(OBJ)/TEST_tools2.o
	$(CXX) $(CXXFLAGS) $^ $(LDFLAGS) -o $@

# rules <?= "\nTEST\n ?>
# copy header to build dir
$(BLD)/%.hpp: $(SRC)/%.hpp
	-cp $^ $@

$(OBJ)/%.o: ./$(SRC)/%.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

#
.PHONY: all clean install unintsall rebuild help

rebuild: clean all

install:
	cp ./$(BLD)/tools2 ./$(prefix)/bin/tools2
uninstall:
	-rm ./$(prefix)/bin/tools2
clean:
	@ECHO "removing files ..."
	-rm -f $(OBJ)/*
	-rm -f $(BLD)/*

help:
	@echo
	@echo  'Project: tools2 : version 0.0.1 : Mon Aug 17 09:38:40 AM CDT 2026 simple "tools2" framework.'
	@echo
	@echo  '    make [-f] [target]'
	@echo
	@echo  '   -Make Targets ...'
	@echo
	@echo  '        * all                              - build all'
	@echo  '        * $(BLD)/tools2:          - re/build tools2'
	@echo  '        * $(BLD)/tools2_utest:    - re/build tools2_utest, unit testing'
	@echo  '        * clean                            - remove most generated files but keep the config'
	@echo
